name: my-env
channels:
- pytorch
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- boost=1.74.0
- boost-cpp=1.74.0
- brotli=1.0.9
- brotli-bin=1.0.9
- bzip2=1.0.8
- ca-certificates=2021.10.8
- cairo=1.16.0
- certifi=2021.10.8
- cycler=0.11.0
- expat=2.4.7
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.13.96
- fonts-conda-ecosystem=1
- fonts-conda-forge=1=0
- fonttools=4.31.2
- freetype=2.10.4
- gettext=0.19.8.1
- giflib=5.2.1
- greenlet=1.1.2
- icu=69.1
- jbig=2.1
- jpeg=9e
- kiwisolver=1.4.0
- lcms2=2.12
- ld_impl_linux-64=2.36.1
- lerc=3.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libdeflate=1.10
- libffi=3.4.2
- libgcc-ng=11.2.0
- libgfortran-ng=11.2.0
- libgfortran5=11.2.0
- libglib=2.70.2
- libgomp=11.2.0
- libiconv=1.16
- liblapack=3.9.0
- libnsl=2.0.0
- libopenblas=0.3.18
- libpng=1.6.37
- libstdcxx-ng=11.2.0
- libtiff=4.3.0
- libuuid=2.32.1
- libwebp=1.2.2
- libwebp-base=1.2.2
- libxcb=1.13
- libzlib=1.2.11
- lz4-c=1.9.3
- matplotlib-base=3.5.1
- munkres=1.1.4
- ncurses=6.3
- numpy=1.22.3
- openjpeg=2.4.0
- openssl=3.0.2
- packaging=21.3
- pandas=1.4.1
- pcre=8.45
- pillow=9.0.1
- pip=22.0.4
- pixman=0.40.0
- pthread-stubs=0.4
- pycairo=1.21.0
- pyparsing=3.0.7
- python=3.8.13
- python-dateutil=2.8.2
- python_abi=3.8
- pytz=2022.1
- rdkit=2021.09.5
- readline=8.1
- reportlab=3.5.68
- setuptools=60.10.0
- six=1.16.0
- sqlalchemy=1.4.32
- sqlite=3.37.1
- tk=8.6.12
- unicodedata2=14.0.0
- wheel=0.37.1
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.5
- zlib=1.2.11
- zstd=1.5.2
- scipy=1.8.0
- pytorch=1.7.1
- torchaudio=0.7.2
- torchvision=0.2.2
- blas=1.0
- ninja=1.7.2
- _pytorch_select=0.2
- cffi=1.15.0
- cudatoolkit=11.0.221
- intel-openmp=2019.4
- joblib=1.1.0
- libmklml=2019.0.5
- libuv=1.40.0
- mkl=2020.2
- pycparser=2.21
- scikit-learn=1.0.2
- threadpoolctl=2.2.0
- typing-extensions=4.1.1
- typing_extensions=4.1.1


